name: Full CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm test

  test-blockchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx hardhat test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # install all three projects
      - name: Install frontend deps
        run: cd frontend && npm ci
      - name: Install backend deps
        run: cd backend && npm ci
      - name: Install blockchain deps
        run: cd blockchain && npm ci

      # install Playwright browsers
      - name: Install Playwright deps
        run: cd frontend && npx playwright install --with-deps

      # start all services
      - name: Start services
        run: |
          cd backend && npm run start &    # backend on 3001
          cd ../blockchain && npx hardhat node &     # node on 8545
          cd ../frontend && npm run dev &    # frontend on 5173

      # wait for endpoints
      - name: Wait for services to be ready
        run: |
          npx wait-on --timeout 60000 http://127.0.0.1:3001
          npx wait-on --timeout 60000 tcp:127.0.0.1:8545
          npx wait-on --timeout 60000 http://127.0.0.1:5173

      # run tests
      - name: Run frontend (Synpress & Playwright) tests
        run: |
          cd frontend
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx synpress
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
