name: Full CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run backend tests
        run: npm test

  test-blockchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blockchain
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run Hardhat tests
        run: npx hardhat test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright deps
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Install blockchain deps
        working-directory: blockchain
        run: npm ci

      - name: Start backend and blockchain
        run: |
          # Start backend
          cd backend
          npm run start &

          # Start blockchain
          cd ../blockchain
          npx hardhat node &

      - name: Wait for backend and blockchain
        run: npx wait-on --timeout 60000 http://127.0.0.1:3001 tcp:127.0.0.1:8545

      - name: Run frontend (Synpress & Playwright) tests with xvfb
        working-directory: frontend
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx synpress
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/

